### PR TITLE
WriteOwned::writev: Return early in case of partial writes

### LINKED ISSUE #72: WriteOwned and write
Hi. What's your take on whether or not writev should be interpreted as a write all?

I suspect most people would say it shouldn't be, as there is a count being returned.

So if an implementation wants to simulate a writev with a looping write, should it check the length of each write result and exit the loop early if the write wasn't complete?

And in the case of the owned API, should it have to rebuild the Vec<B> so all the entries are there for the caller to reuse, perhaps after modifying the vec slice and one of the vec entry slices?

Since the input vec argument ownership is passed in, it seems reasonable to replace the entries per write but I haven't tried to play with that yet to see how easy the ownership is kept straight, without resorting to unsafe.

### PR DESCRIPTION
**Pull request by fasterthanlime**
Closes #72

### CODE REVIEW

**Comment by fasterthanlime** [comment]
I'm working on a proper `writev_all` method, but advancing buffers is a headache 🙃 

I was keeping that little `unimplemented!` as a surprise for myself later...

**Comment by fasterthanlime** [comment]
> Maybe you've already solved the segfault. And the root cause of it is certainly interesting

I have not, but it is interesting indeed:

```
2023-01-31T18:20:45.691210Z DEBUG hring_bingo_ktls: Connected to httpbingo
WriteOwned::writev_all, calling writev with 13 items
==125831== Use of uninitialised value of size 8
==125831==    at 0x196CB6: hring_buffet::io::WriteOwned::writev::{{closure}} (io.rs:0)
==125831==    by 0x19664B: hring_buffet::io::WriteOwned::writev_all::{{closure}} (io.rs:96)
==125831==    by 0x19ED21: hring::h1::client::request::{{closure}} (client.rs:57)
==125831==    by 0x1DB7B4: <hring_bingo_ktls::SDriver as hring::ServerDriver>::handle::{{closure}} (main.rs:234)
==125831==    by 0x2AAA9D: hring::h2::server::end_headers::{{closure}} (server.rs:764)
==125831==    by 0x2CDEA9: tokio::runtime::task::core::Core<T,S>::poll::{{closure}} (core.rs:223)
==125831==    by 0x1B5A60: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut (unsafe_cell.rs:14)
==125831==    by 0x2CDC85: tokio::runtime::task::core::Core<T,S>::poll (core.rs:212)
==125831==    by 0x21D819: tokio::runtime::task::harness::poll_future::{{closure}} (harness.rs:476)
==125831==    by 0x2DB032: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (unwind_safe.rs:271)
==125831==    by 0x2C867B: std::panicking::try::do_call (panicking.rs:483)
==125831==    by 0x2C99AA: __rust_try (in /home/amos/bearcove/hring/target/debug/hring-bingo-ktls)
==125831== 
WriteOwned::write_v with 👈 ==125831== Conditional jump or move depends on uninitialised value(s)
==125831==    at 0x52CEF6: core::fmt::num::imp::<impl core::fmt::Display for u64>::fmt (num.rs:230)
==125831==    by 0x525D7D: core::fmt::write (mod.rs:1213)
==125831==    by 0x4FE153: <&std::io::stdio::Stderr as std::io::Write>::write_fmt (mod.rs:1682)
==125831==    by 0x4FE97A: std::io::stdio::_eprint (stdio.rs:908)
==125831==    by 0x196EB1: hring_buffet::io::WriteOwned::writev::{{closure}} (io.rs:46)
==125831==    by 0x19664B: hring_buffet::io::WriteOwned::writev_all::{{closure}} (io.rs:96)
==125831==    by 0x19ED21: hring::h1::client::request::{{closure}} (client.rs:57)
==125831==    by 0x1DB7B4: <hring_bingo_ktls::SDriver as hring::ServerDriver>::handle::{{closure}} (main.rs:234)
==125831==    by 0x2AAA9D: hring::h2::server::end_headers::{{closure}} (server.rs:764)
==125831==    by 0x2CDEA9: tokio::runtime::task::core::Core<T,S>::poll::{{closure}} (core.rs:223)
==125831==    by 0x1B5A60: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut (unsafe_cell.rs:14)
==125831==    by 0x2CDC85: tokio::runtime::task::core::Core<T,S>::poll (core.rs:212)
==125831== 
==125831== Conditional jump or move depends on uninitialised value(s)
==125831==    at 0x52CFBF: core::fmt::num::imp::<impl core::fmt::Display for u64>::fmt (num.rs:249)
==125831==    by 0x525D7D: core::fmt::write (mod.rs:1213)
==125831==    by 0x4FE153: <&std::io::stdio::Stderr as std::io::Write>::write_fmt (mod.rs:1682)
==125831==    by 0x4FE97A: std::io::stdio::_eprint (stdio.rs:908)
==125831==    by 0x196EB1: hring_buffet::io::WriteOwned::writev::{{closure}} (io.rs:46)
==125831==    by 0x19664B: hring_buffet::io::WriteOwned::writev_all::{{closure}} (io.rs:96)
==125831==    by 0x19ED21: hring::h1::client::request::{{closure}} (client.rs:57)
==125831==    by 0x1DB7B4: <hring_bingo_ktls::SDriver as hring::ServerDriver>::handle::{{closure}} (main.rs:234)
==125831==    by 0x2AAA9D: hring::h2::server::end_headers::{{closure}} (server.rs:764)
==125831==    by 0x2CDEA9: tokio::runtime::task::core::Core<T,S>::poll::{{closure}} (core.rs:223)
==125831==    by 0x1B5A60: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut (unsafe_cell.rs:14)
==125831==    by 0x2CDC85: tokio::runtime::task::core::Core<T,S>::poll (core.rs:212)
==125831== 
==125831== Conditional jump or move depends on uninitialised value(s)
==125831==    at 0x52CFAB: core::fmt::num::imp::<impl core::fmt::Display for u64>::fmt (num.rs:257)
==125831==    by 0x525D7D: core::fmt::write (mod.rs:1213)
==125831==    by 0x4FE153: <&std::io::stdio::Stderr as std::io::Write>::write_fmt (mod.rs:1682)
==125831==    by 0x4FE97A: std::io::stdio::_eprint (stdio.rs:908)
==125831==    by 0x196EB1: hring_buffet::io::WriteOwned::writev::{{closure}} (io.rs:46)
==125831==    by 0x19664B: hring_buffet::io::WriteOwned::writev_all::{{closure}} (io.rs:96)
==125831==    by 0x19ED21: hring::h1::client::request::{{closure}} (client.rs:57)
==125831==    by 0x1DB7B4: <hring_bingo_ktls::SDriver as hring::ServerDriver>::handle::{{closure}} (main.rs:234)
==125831==    by 0x2AAA9D: hring::h2::server::end_headers::{{closure}} (server.rs:764)
==125831==    by 0x2CDEA9: tokio::runtime::task::core::Core<T,S>::poll::{{closure}} (core.rs:223)
==125831==    by 0x1B5A60: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut (unsafe_cell.rs:14)
==125831==    by 0x2CDC85: tokio::runtime::task::core::Core<T,S>::poll (core.rs:212)
==125831== 
==125831== Syscall param write(buf) points to uninitialised byte(s)
==125831==    at 0x4A81D94: write (write.c:26)
==125831==    by 0x4FE2FE: <std::io::stdio::StderrLock as std::io::Write>::write_all (fd.rs:152)
==125831==    by 0x4FF5D5: <std::io::Write::write_fmt::Adapter<T> as core::fmt::Write>::write_str (mod.rs:1671)
==125831==    by 0x52CFFD: core::fmt::num::imp::<impl core::fmt::Display for u64>::fmt (num.rs:273)
==125831==    by 0x525D7D: core::fmt::write (mod.rs:1213)
==125831==    by 0x4FE153: <&std::io::stdio::Stderr as std::io::Write>::write_fmt (mod.rs:1682)
==125831==    by 0x4FE97A: std::io::stdio::_eprint (stdio.rs:908)
==125831==    by 0x196EB1: hring_buffet::io::WriteOwned::writev::{{closure}} (io.rs:46)
==125831==    by 0x19664B: hring_buffet::io::WriteOwned::writev_all::{{closure}} (io.rs:96)
==125831==    by 0x19ED21: hring::h1::client::request::{{closure}} (client.rs:57)
==125831==    by 0x1DB7B4: <hring_bingo_ktls::SDriver as hring::ServerDriver>::handle::{{closure}} (main.rs:234)
==125831==    by 0x2AAA9D: hring::h2::server::end_headers::{{closure}} (server.rs:764)
==125831==  Address 0x1ffeff3187 is on thread 1's stack
==125831==  in frame #3, created by core::fmt::num::imp::<impl core::fmt::Display for u64>::fmt (num.rs:279)
==125831== 
2 buffers 👈
```

> But two things: maybe you want to allow for a zero length buffer in the writev loop either by skipping buffers that are zero length, or by checking the buf_len wasn't zero to begin with before returning an error.

I've considered this but am happy with the current design for now.

>  And the writev_all could maybe be easier if you copy your write_all default and essentially replace the calls to write with calls to write_all.

But `writev_all` should call `writev` to take advantage of vectored writes, not `write`, right?

**Comment by FrankReh** [comment]
> I've considered this but am happy with the current design for now.

Just double checking. You're okay with it because you know you don't ever pass zero length buffers to writev.

> But writev_all should call writev to take advantage of vectored writes, not write, right?

That's a good point. I forgot your TcpStream has a specific writev it can make. By the way, there is a write_all it can call directly too but it may not be better than what you are already doing. We don't have a writev_all. But will probably follow the tokio lead of a write_vectored and the std lead of write_all_vectored down the road.

**Comment by fasterthanlime** [comment]
So this is blocked on https://github.com/rust-lang/rust/pull/107013 - I'm checking that the fix does fix our issue.

**Pull request merged**
